<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="4" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="95387" started-at="2018-07-13T07:10:09Z" finished-at="2018-07-13T07:11:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="95387" started-at="2018-07-13T07:10:09Z" finished-at="2018-07-13T07:11:44Z">
      <class name="com.ddfw.punj.testcases.TestCaseA">
        <test-method status="PASS" signature="initsoft()[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="initsoft" is-config="true" duration-ms="20" started-at="2018-07-13T17:11:30Z" finished-at="2018-07-13T17:11:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initsoft -->
        <test-method status="FAIL" signature="testA(java.util.Hashtable)[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="testA" duration-ms="23" started-at="2018-07-13T17:11:30Z" data-provider="getData" finished-at="2018-07-13T17:11:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col3=A3, Runmode=N, col2=A2, col1=A1}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.ddfw.punj.testcases.TestCaseA.testA(TestCaseA.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="PASS" signature="extentquit()[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="extentquit" is-config="true" duration-ms="405" started-at="2018-07-13T17:11:31Z" finished-at="2018-07-13T17:11:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentquit -->
        <test-method status="PASS" signature="initsoft()[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="initsoft" is-config="true" duration-ms="0" started-at="2018-07-13T17:11:31Z" finished-at="2018-07-13T17:11:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initsoft -->
        <test-method status="FAIL" signature="testA(java.util.Hashtable)[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="testA" duration-ms="2" started-at="2018-07-13T17:11:31Z" data-provider="getData" finished-at="2018-07-13T17:11:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col3=A6, Runmode=N, col2=A5, col1=A4}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.ddfw.punj.testcases.TestCaseA.testA(TestCaseA.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="PASS" signature="extentquit()[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="extentquit" is-config="true" duration-ms="40" started-at="2018-07-13T17:11:31Z" finished-at="2018-07-13T17:11:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentquit -->
        <test-method status="PASS" signature="initsoft()[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="initsoft" is-config="true" duration-ms="0" started-at="2018-07-13T17:11:31Z" finished-at="2018-07-13T17:11:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initsoft -->
        <test-method status="FAIL" signature="testA(java.util.Hashtable)[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="testA" duration-ms="3" started-at="2018-07-13T17:11:31Z" data-provider="getData" finished-at="2018-07-13T17:11:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col3=A9, Runmode=Y, col2=A8, col1=A7}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.ddfw.punj.testcases.TestCaseA.testA(TestCaseA.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="PASS" signature="extentquit()[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="extentquit" is-config="true" duration-ms="38" started-at="2018-07-13T17:11:31Z" finished-at="2018-07-13T17:11:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentquit -->
        <test-method status="PASS" signature="initsoft()[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="initsoft" is-config="true" duration-ms="0" started-at="2018-07-13T17:11:31Z" finished-at="2018-07-13T17:11:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initsoft -->
        <test-method status="FAIL" signature="TestA1()[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="TestA1" duration-ms="12882" started-at="2018-07-13T17:11:31Z" finished-at="2018-07-13T17:11:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Locator not correct- signin_xpath]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Locator not correct- signin_xpath
	at org.testng.Assert.fail(Assert.java:94)
	at com.ddfw.punj.base.BaseTest.reportFailure(BaseTest.java:202)
	at com.ddfw.punj.base.BaseTest.getElement(BaseTest.java:110)
	at com.ddfw.punj.base.BaseTest.verifyText(BaseTest.java:180)
	at com.ddfw.punj.testcases.TestCaseA.TestA1(TestCaseA.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestA1 -->
        <test-method status="PASS" signature="extentquit()[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="extentquit" is-config="true" duration-ms="58" started-at="2018-07-13T17:11:44Z" finished-at="2018-07-13T17:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentquit -->
        <test-method status="SKIP" signature="TestA2()[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="TestA2" duration-ms="16" started-at="2018-07-13T17:11:44Z" depends-on-methods="com.ddfw.punj.testcases.TestCaseA.TestA1" finished-at="2018-07-13T17:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestA2 -->
        <test-method status="SKIP" signature="TestA3()[pri:0, instance:com.ddfw.punj.testcases.TestCaseA@26b3fd41]" name="TestA3" duration-ms="1" started-at="2018-07-13T17:11:44Z" depends-on-methods="com.ddfw.punj.testcases.TestCaseA.TestA1, com.ddfw.punj.testcases.TestCaseA.TestA2" finished-at="2018-07-13T17:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestA3 -->
      </class> <!-- com.ddfw.punj.testcases.TestCaseA -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
